export const nexloid = {
  FETCH_ALL_ARTICLES: "FETCH_ALL_ARTICLES",
  FETCH_LATEST_ARTICLES: "FETCH_LATEST_ARTICLES",
  FETCH_AN_ARTICLE: "FETCH_AN_ARTICLE",
  FETCH_RELATED_ARTICLES: "FETCH_RELATED_ARTICLES",

  FETCH_ALL_WORKS: "FETCH_ALL_WORKS",
  FETCH_LATEST_WORKS: "FETCH_LATEST_WORKS",
  FETCH_A_WORK: "FETCH_A_WORK",
  FETCH_RELATED_WORKS: "FETCH_RELATED_WORKS",

  FETCH_SERVICE_DETAILS: "FETCH_SERVICE_DETAILS",
  FETCH_ALL_SERVICES: "FETCH_ALL_SERVICES",

  FETCH_CAREERS: "FETCH_CAREERS",

  APP_LOADING: "APP_LOADING",
  TOGGLE_CONTACT_US: "TOGGLE_CONTACT_US",
  TOGGLE_CAREER_FORM: "TOGGLE_CAREER_FORM",

  CLEAR_OPENED_SERVICE: "CLEAR_OPENED_SERVICE"
};
